# Generated by Django 5.2.13 on 2026-05-05 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('service', models.CharField(max_length=20)),
                ('budget', models.CharField(max_length=10)),
                ('note', models.TextField(null=True)),
            ],
        ),
    ]
